version: 2
jobs:
  build:
    working_directory: ~/ietty/maps
    parallelism: 1
    shell: /bin/bash --login

    docker:
    - image: ietty/centos7-npm
      command: /sbin/init

    steps:
    - checkout

    - run:
        name: install python-pip & awscli
        command: |
          sudo yum -y install python-pip
          sudo pip install awscli

    - run:
        name: set aws config
        command: |
          aws configure set region ap-northeast-1
          aws configure set preview.cloudfront true

    # Test
    - run: echo "Nothing to do here"

    # Deployment
    - deploy:
        name: aws s3 sync
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            aws s3 sync public/ s3://maps.ietty.me/ --delete
            aws cloudfront create-invalidation --distribution-id E13541DGV2P35 --paths '/*'
          elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
            aws s3 sync public/ s3://maps.ietty.estate/ --delete
            #aws cloudfront create-invalidation --distribution-id E25WT09WBX39FL --paths '/*'
          fi

